
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}
  name: {{ .Values.app_name }}
  namespace: {{ .Values.app_name }}
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30007
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.app_name }}
  sessionAffinity: None
  type: LoadBalancer
